# 데이터 불러오기

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from tqdm.notebook import tqdm
import json
import re

In [27]:
df_final = pd.read_csv('/content/drive/MyDrive/csv/df_final.csv', index_col = 0)
df_final = df_final.reset_index()
df_final = df_final.drop('index', axis = 1)
df_final = df_final.drop('Unnamed: 0.1', axis = 1)

In [28]:
df_final

           상품번호  성별      키   몸무게 구매한 사이즈   평점        구매날짜
0       1778404  **  ***cm  **kg       M  5.0        3분 전
1       1778404  남성  170cm  64kg       L  5.0       1시간 전
2       1778404  여성  155cm  55kg   S(기모)  5.0       1시간 전
3       1778404  남성  170cm  60kg       M  5.0       1시간 전
4       1778404  남성  173cm  65kg      XL  5.0       2시간 전
...         ...  ..    ...   ...     ...  ...         ...
729191  1547899  남성  178cm  81kg       L  5.0  2022.01.02
729192  1547899  남성  169cm  65kg       M  4.0  2022.01.02
729193  1547899  남성  175cm  71kg       M  5.0  2022.01.01
729194  1547899  남성  168cm  73kg       M  4.0  2022.01.01
729195  1547899  **  ***cm  **kg       M  5.0  2021.12.31

[729196 rows x 7 columns]

# 1월1일부터 3월31일까지를 제외한 데이터 제거

In [29]:
index1 = df_final[df_final['구매날짜']=='2021.12.31'].index
df = df_final.drop(index1)

In [30]:
del_lists = ['분', '시간', '1일', '2일', '3일', '4일', '5일', '6일', 
             '2021.', '2020.', '2019.', '2018.', '2017.', '2016.', '2015.', '2014.', '2013.', '2012.', '2011.', '2010.']

for del_list in del_lists:
  df = df[~df['구매날짜'].str.contains(del_list)]

In [31]:
df = df.reset_index()
df = df.drop('index', axis = 1)
df.index = df.index+1
df

           상품번호  성별      키   몸무게 구매한 사이즈   평점        구매날짜
1       1778404  **  ***cm  **kg       L  4.0        7일 전
2       1778404  남성  182cm  72kg      XL  2.0        7일 전
3       1778404  남성  183cm  80kg      XL  5.0        7일 전
4       1778404  남성  177cm  62kg       L  5.0        7일 전
5       1778404  남성  174cm  67kg       L  5.0        7일 전
...         ...  ..    ...   ...     ...  ...         ...
442445  1547899  남성  178cm  76kg       M  5.0  2022.01.02
442446  1547899  남성  178cm  81kg       L  5.0  2022.01.02
442447  1547899  남성  169cm  65kg       M  4.0  2022.01.02
442448  1547899  남성  175cm  71kg       M  5.0  2022.01.01
442449  1547899  남성  168cm  73kg       M  4.0  2022.01.01

[442449 rows x 7 columns]